TensorBoardLogger: /home/x2020fpt/projects/def-jlevman/x2020fpt/rUnet_CC_3
activation: LeakyReLU
batch_size: 3
checkpoint_file: null
clip_max: 5
clip_min: 2
fast_dev_run: false
fine_tune: false
gpus: 1
in_channels: 3
kfold_num: 3
learning_rate: 1.0e-05
loss: l2
normalization: InstanceNorm3d
num_rep: 1
task: longitudinal
use_data_augmentation: false
weight_decay: 1.0e-08
